environments:
  FMC-Test7.2.0:
    'host': "192.168.3.37"
    'username': "apiuser"
    'password': "Iching12"
  FTD-Test7.2.0:
    'host': "192.168.3.38"
    'username': "admin"
    'password': "Iching12#"